In [1]:
import warnings
warnings.filterwarnings('ignore')
import os
import numpy as np
import pandas as pd
import json
import re
import folium
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
sns.set_style("whitegrid")
sns.set_context("paper")
plt.style.use('seaborn')

In [2]:
path=r'/Users/marieanek2/Documents/Youtube Trending Analysis'

In [3]:
#Datasets
df_USA= pd.read_csv(os.path.join(path,'02 Data','Original Data','USvideos.csv'),index_col = False)

df_Russia= pd.read_csv(os.path.join(path,'02 Data','Original Data','RUvideos.csv'),index_col = False)

df_Canada= pd.read_csv(os.path.join(path,'02 Data','Original Data','CAvideos.csv'),index_col = False)

df_Germany= pd.read_csv(os.path.join(path,'02 Data','Original Data','DEvideos.csv'),index_col = False)

df_France= pd.read_csv(os.path.join(path,'02 Data','Original Data','FRvideos.csv'),index_col = False)

df_UK= pd.read_csv(os.path.join(path,'02 Data','Original Data','GBvideos.csv'),index_col = False)

df_Mexico= pd.read_csv(os.path.join(path,'02 Data','Original Data','MXvideos.csv'),index_col = False)

df_Japan= pd.read_csv(os.path.join(path,'02 Data','Original Data','JPvideos.csv'),index_col = False)

In [4]:
# Iporting json files
USA_categories=('r/Users/marieanek2/Documents/Youtube Trending Analysis/US_category_id.json')
RU_categories=('r/Users/marieanek2/Documents/Youtube Trending Analysis/RU_category_id.json')
CA_categories=('r/Users/marieanek2/Documents/Youtube Trending Analysis/CA_category_id.json')
DE_categories=('r/Users/marieanek2/Documents/Youtube Trending Analysis/DE_category_id.json')
FR_categories=('r/Users/marieanek2/Documents/Youtube Trending Analysis/FR_category_id.json')
GB_categories=('r/Users/marieanek2/Documents/Youtube Trending Analysis/GB_category_id.json')
MX_categories=('r/Users/marieanek2/Documents/Youtube Trending Analysis/MX_category_id.json')
JP_categories=('r/Users/marieanek2/Documents/Youtube Trending Analysis/JP_category_id.json')

In [5]:
id_to_cat = {}

with open('/Users/marieanek2/Documents/Youtube Trending Analysis/02 Data/Original Data/US_category_id.json', 'r') as f:
   data= json.load(f)

for category in data['items']:
    id_to_cat[category['id']] = category['snippet']['title']

In [6]:
id_to_cat = {}

with open('/Users/marieanek2/Documents/Youtube Trending Analysis/02 Data/Original Data/RU_category_id.json', 'r') as f:
   data= json.load(f)

for category in data['items']:
    id_to_cat[category['id']] = category['snippet']['title']

In [7]:
id_to_cat = {}

with open('/Users/marieanek2/Documents/Youtube Trending Analysis/02 Data/Original Data/CA_category_id.json', 'r') as f:
   data= json.load(f)

for category in data['items']:
    id_to_cat[category['id']] = category['snippet']['title']

In [8]:
id_to_cat = {}

with open('/Users/marieanek2/Documents/Youtube Trending Analysis/02 Data/Original Data/DE_category_id.json', 'r') as f:
   data= json.load(f)

for category in data['items']:
    id_to_cat[category['id']] = category['snippet']['title']

In [9]:
id_to_cat = {}

with open('/Users/marieanek2/Documents/Youtube Trending Analysis/02 Data/Original Data/FR_category_id.json', 'r') as f:
   data= json.load(f)

for category in data['items']:
    id_to_cat[category['id']] = category['snippet']['title']

In [10]:
id_to_cat = {}

with open('/Users/marieanek2/Documents/Youtube Trending Analysis/02 Data/Original Data/MX_category_id.json', 'r') as f:
   data= json.load(f)

for category in data['items']:
    id_to_cat[category['id']] = category['snippet']['title']

In [11]:
id_to_cat = {}

with open('/Users/marieanek2/Documents/Youtube Trending Analysis/02 Data/Original Data/JP_category_id.json', 'r') as f:
   data= json.load(f)

for category in data['items']:
    id_to_cat[category['id']] = category['snippet']['title']

In [12]:
id_to_cat = {}

with open('/Users/marieanek2/Documents/Youtube Trending Analysis/02 Data/Original Data/GB_category_id.json', 'r') as f:
   data= json.load(f)

for category in data['items']:
    id_to_cat[category['id']] = category['snippet']['title']

In [13]:
id_to_cat

{'1': 'Film & Animation',
 '2': 'Autos & Vehicles',
 '10': 'Music',
 '15': 'Pets & Animals',
 '17': 'Sports',
 '18': 'Short Movies',
 '19': 'Travel & Events',
 '20': 'Gaming',
 '21': 'Videoblogging',
 '22': 'People & Blogs',
 '23': 'Comedy',
 '24': 'Entertainment',
 '25': 'News & Politics',
 '26': 'Howto & Style',
 '27': 'Education',
 '28': 'Science & Technology',
 '30': 'Movies',
 '31': 'Anime/Animation',
 '32': 'Action/Adventure',
 '33': 'Classics',
 '34': 'Comedy',
 '35': 'Documentary',
 '36': 'Drama',
 '37': 'Family',
 '38': 'Foreign',
 '39': 'Horror',
 '40': 'Sci-Fi/Fantasy',
 '41': 'Thriller',
 '42': 'Shorts',
 '43': 'Shows',
 '44': 'Trailers'}

In [14]:
##Merging datasets into one.


df_countriescombined= pd.concat([df_USA,df_Russia,df_Canada,df_Germany,df_France,df_UK,df_Mexico,df_Japan],axis=0)

In [15]:
df_countriescombined.head()

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description
0,2kyS6SvSYSE,17.14.11,WE WANT TO TALK ABOUT OUR MARRIAGE,CaseyNeistat,22,2017-11-13T17:13:01.000Z,SHANtell martin,748374,57527,2966,15954,https://i.ytimg.com/vi/2kyS6SvSYSE/default.jpg,False,False,False,SHANTELL'S CHANNEL - https://www.youtube.com/s...
1,1ZAPwfrtAFY,17.14.11,The Trump Presidency: Last Week Tonight with J...,LastWeekTonight,24,2017-11-13T07:30:00.000Z,"last week tonight trump presidency|""last week ...",2418783,97185,6146,12703,https://i.ytimg.com/vi/1ZAPwfrtAFY/default.jpg,False,False,False,"One year after the presidential election, John..."
2,5qpjK5DgCt4,17.14.11,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,2017-11-12T19:05:24.000Z,"racist superman|""rudy""|""mancuso""|""king""|""bach""...",3191434,146033,5339,8181,https://i.ytimg.com/vi/5qpjK5DgCt4/default.jpg,False,False,False,WATCH MY PREVIOUS VIDEO ▶ \n\nSUBSCRIBE ► http...
3,puqaWrEC7tY,17.14.11,Nickelback Lyrics: Real or Fake?,Good Mythical Morning,24,2017-11-13T11:00:04.000Z,"rhett and link|""gmm""|""good mythical morning""|""...",343168,10172,666,2146,https://i.ytimg.com/vi/puqaWrEC7tY/default.jpg,False,False,False,Today we find out if Link is a Nickelback amat...
4,d380meD0W0M,17.14.11,I Dare You: GOING BALD!?,nigahiga,24,2017-11-12T18:01:41.000Z,"ryan|""higa""|""higatv""|""nigahiga""|""i dare you""|""...",2095731,132235,1989,17518,https://i.ytimg.com/vi/d380meD0W0M/default.jpg,False,False,False,I know it's been a while since we did this sho...

In [16]:
# Inserting the country column

df_USA['country']='US'
df_Germany['country']='DE'
df_France['country']='FR'
df_Japan['country']='JP'
df_UK['country']='GB'
df_Canada['country']='CA'
df_Russia['country']= 'RU'
df_Mexico['country']='MX'

In [17]:
df_countriescombined=pd.concat([df_USA,df_Russia,df_Japan,df_Canada,df_Germany,df_UK,df_Mexico,df_France])

In [18]:
df_countriescombined.head(3)

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country
0,2kyS6SvSYSE,17.14.11,WE WANT TO TALK ABOUT OUR MARRIAGE,CaseyNeistat,22,2017-11-13T17:13:01.000Z,SHANtell martin,748374,57527,2966,15954,https://i.ytimg.com/vi/2kyS6SvSYSE/default.jpg,False,False,False,SHANTELL'S CHANNEL - https://www.youtube.com/s...,US
1,1ZAPwfrtAFY,17.14.11,The Trump Presidency: Last Week Tonight with J...,LastWeekTonight,24,2017-11-13T07:30:00.000Z,"last week tonight trump presidency|""last week ...",2418783,97185,6146,12703,https://i.ytimg.com/vi/1ZAPwfrtAFY/default.jpg,False,False,False,"One year after the presidential election, John...",US
2,5qpjK5DgCt4,17.14.11,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,2017-11-12T19:05:24.000Z,"racist superman|""rudy""|""mancuso""|""king""|""bach""...",3191434,146033,5339,8181,https://i.ytimg.com/vi/5qpjK5DgCt4/default.jpg,False,False,False,WATCH MY PREVIOUS VIDEO ▶ \n\nSUBSCRIBE ► http...,US

In [19]:
#Changing date format.
df_countriescombined['trending_date'] = pd.to_datetime(df_countriescombined['trending_date'], format='%y.%d.%m')

In [20]:
# Changing time format
df_countriescombined['publish_time'] = pd.to_datetime(df_countriescombined['publish_time'], format='%Y-%m-%dT%H:%M:%S.%fZ')

In [21]:
df_countriescombined['category_id'] = df_countriescombined['category_id'].astype(str)

In [22]:
df_countriescombined.insert(5, 'category', df_countriescombined['category_id'].map(id_to_cat))

In [23]:
df_countriescombined['category'] =df_countriescombined['category_id'].map(id_to_cat)

In [24]:
df_countriescombined.head(1)

,video_id,trending_date,title,channel_title,category_id,category,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country
0,2kyS6SvSYSE,2017-11-14,WE WANT TO TALK ABOUT OUR MARRIAGE,CaseyNeistat,22,People & Blogs,2017-11-13 17:13:01,SHANtell martin,748374,57527,2966,15954,https://i.ytimg.com/vi/2kyS6SvSYSE/default.jpg,False,False,False,SHANTELL'S CHANNEL - https://www.youtube.com/s...,US

In [25]:
df_countriescombined.tail(2)

,video_id,trending_date,title,channel_title,category_id,category,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country
40722,NlxE_QQMRzg,2018-06-14,"Նռան հատիկ, Սերիա 192 / Pomegranate seed / Nra...",PanArmenian TV,1,Film & Animation,2018-06-13 18:30:00,"Նռան հատիկ|""Սերիա 192""|""Pomegranate seed""|""Nra...",78117,244,74,46,https://i.ytimg.com/vi/NlxE_QQMRzg/default.jpg,False,False,False,Follow Armenia TV on social platforms:Instagra...,FR
40723,_LgKglfnqlc,2018-06-14,Mandoumbé ak Koor Gui 2018 Episode 28,Yesdakar,24,Entertainment,2018-06-13 19:45:14,"ramadan2018|""koorgui""|""Mandoumbé""",46604,947,37,127,https://i.ytimg.com/vi/_LgKglfnqlc/default.jpg,False,False,False,NaN,FR

In [26]:
# Choosing only columns i need
df_ALL=df_countriescombined[['country','channel_title','title','category','views', 'likes', 'dislikes','comment_count', 'comments_disabled', 
                  'ratings_disabled','video_error_or_removed','trending_date','publish_time']]

In [27]:
df_ALL.head(2)

,country,channel_title,title,category,views,likes,dislikes,comment_count,comments_disabled,ratings_disabled,video_error_or_removed,trending_date,publish_time
0,US,CaseyNeistat,WE WANT TO TALK ABOUT OUR MARRIAGE,People & Blogs,748374,57527,2966,15954,False,False,False,2017-11-14,2017-11-13 17:13:01
1,US,LastWeekTonight,The Trump Presidency: Last Week Tonight with J...,Entertainment,2418783,97185,6146,12703,False,False,False,2017-11-14,2017-11-13 07:30:00

In [28]:
#Checking for null values
df_ALL.isna().sum()

country                      0
channel_title                0
title                        0
category                  2402
views                        0
likes                        0
dislikes                     0
comment_count                0
comments_disabled            0
ratings_disabled             0
video_error_or_removed       0
trending_date                0
publish_time                 0
dtype: int64

In [29]:
# Removing the null values
df_ALL=df_ALL.dropna()

In [30]:
#Checking again
df_ALL.isna().sum()

country                   0
channel_title             0
title                     0
category                  0
views                     0
likes                     0
dislikes                  0
comment_count             0
comments_disabled         0
ratings_disabled          0
video_error_or_removed    0
trending_date             0
publish_time              0
dtype: int64

In [33]:
# Export cleaned data set  to csv
df_ALL.to_csv(os.path.join(path, '02 Data','Prepared Data', 'df_ALL.csv'))

In [34]:
# Export Data to csv
df_countriescombined.to_csv(os.path.join(path, '02 Data','Prepared Data', 'df_ALLcolumns.csv'))